import { connection, connect } from "../configs/mySQL.js";

class EspejoModel {
  getTriggerModel = async () => {
    const [query] = await connection.query("SELECT * FROM TB_PEDIDOS_TRIGGRER");
    return query;
  };

  getEspejoModel = async (barcode) => {
    const [query] = await connect.query(
      "SELECT * FROM TB_PEDIDOS WHERE TB_PEDIDOS_BARCODE_CAJA IN (?)",
      [barcode]
    );

    return query;
  };

  deleteTriggerModel = async (barcode) => {
    const [query] = await connection.query(
      "DELETE FROM TB_PEDIDOS_TRIGGRER WHERE TB_PEDIDOS_BARCODE_CAJA IN (?)",
      [barcode]
    );

    return query;
  };

  InsertEspejo = async (datos) => {
    const [query] = await connect.query(
      "INSERT INTO TB_PEDIDOS (CODIGO_PK, TB_PEDIDOS_NIT, TB_PEDIDOS_CLIENTE, TB_PEDIDOS_MARCA, TB_PEDIDOS_CODIGO_ZONA, TB_PEDIDOS_NOMBRE_ZONA, TB_PEDIDOS_CIUDAD, TB_PEDIDOS_CAMPANA, TB_PEDIDOS_FECHA, TB_PEDIDOS_NRO_FACTURA, TB_PEDIDOS_NRO_PEDIDO, TB_PEDIDOS_CONSECUTIVO, TB_PEDIDOS_BARCODE_CAJA, TB_PEDIDOS_TIPO_PRODUCTO, TB_PEDIDOS_CONTENIDO_CAJA, TB_PEDIDOS_ID_ASESORA, TB_PEDIDOS_CEDULA, TB_PEDIDOS_NOMBRE_ASESORA, TB_PEDIDOS_DIRECCION_ASESORA, TB_PEDIDOS_DPTO_ASESORA, TB_PEDIDOS_BARRIO_ASESORA, TB_PEDIDOS_VEREDA, TB_PEDIDOS_MUNICIPIO_ENVIEXPRESS, TB_PEDIDOS_CELULAR_ASESORA, TB_PEDIDOS_MOVIL_ASESORA, TB_PEDIDOS_AUDITAR, TB_PEDIDOS_CAJAS, TIEMPO_TRANSITO_BODEGA, TIEMPO_BODEGA_REPARTO, TIEMPO_BODEGA_DIGITALIZADO, TIEMPO_TRANSITO_DIGITALIZADO, TIEMPO_REPARTO_DIGITALIZADO, TIPO_DE_CARGA, TIPO_DESTINO, PROMESA_HRS, ANS, METODO_DE_PAGO, ESTADO, EN_BODEGA_FECHA, EN_REPARTO_FECHA, ESTADO_ENTREGADO, EN_ENTREGADO_FECHA, DIGITALIZADO_FECHA, SINIESTRO_FECHA, ESTADO_DIGITALIZADO, ESTADO_NO_ENTREGADO, EN_NO_ENTREGADO_FECHA, ESTADO_REENVIO, EN_REENVIO_FECHA, EN_RETORNO_FECHA, REZAGO_FECHA, NOVEDAD, NOTA, NOTAS_DE_OPERACION, CEDI, ACTIVO, FECHA_HORA, FECHA, CODIGO_DE_CARGA, ORDEN_DE_SERVICIO, ORDEN_DE_DESPACHO, PLACA, PLACA_DE_REPARTO, TRANSPORTADOR, FECHA_CARGA, ENCONTRADO_EN_CONTEO, CONSECUTIVO_CONTEO, CODIGO_DE_CARGUE, MANIFIESTO_URBANO, CODIGO_DE_REENVIO, CODIGO_DE_RETORNO, ESTADO_SEGMENTACION_DE_CONTEO, ESTADO_CODIGO_DE_ZONA, CODIGO_CIUDAD, MAIL_GROUP, PLACA_MP, NOMBRE_CONDUCTOR, LINK, FOTOGRAFIA, TEST, USUARIO_REGISTRO, USUARIO_EN_BODEGA, USUARIO_EN_REPARTO, TOKEN, DESPACHO_API, DESPACHO_ID, CODE_STATUS, EN_TRANSBORDO_FECHA, CHECK_TRANSITO, CHECK_TRANSITO_A_CEDI, CHECK_EN_BODEGA_VERIFICACION, CHECK_EN_BODEGA, CHECK_EN_REPARTO, CHECK_DIGITALIZADO, RADICADO, RADICADOSC, ESTADO_MOVE, ESTADO_MOVE_RECORDS, ESTADO_MOVE_EC, CODIGO_FLETE, VR_UNITARIO_DIST, VR_UNITARIO_VEREDA_DIST, VR_ADICIONAL_DIST, VR_FLETE_DIST, OTROS_COSTOS_DIST, PRE_LIQUIDACION, FECHA_PRE_LIQUIDACION, ESTADO_PRE_LIQUIDACION, REGISTRO_MOVIDO_PRE_LIQUIDACION, ORDEN_DE_COMPRA, FECHA_ORDEN_DE_COMPRA, VR_FAC, VR_FTE_FAC, NO_FAC, FECHA_FAC, ESTADO_TRACKING, ESTADO_PRELIQUIDACION, NTF_EN_REPARTO, NTF_DIGITALIZADO) VALUES ?",
      [datos]
    );

    return query;
  };

  updateEspejo = async (datos) => {
    const [query] = await connect.query(
      "UPDATE TB_PEDIDOS SET TB_PEDIDOS_NIT=?,TB_PEDIDOS_CLIENTE=?,TB_PEDIDOS_MARCA=?,TB_PEDIDOS_CODIGO_ZONA=?,TB_PEDIDOS_NOMBRE_ZONA=?,TB_PEDIDOS_CIUDAD=?,TB_PEDIDOS_CAMPANA=?,TB_PEDIDOS_FECHA=?,TB_PEDIDOS_NRO_FACTURA=?,TB_PEDIDOS_NRO_PEDIDO=?,TB_PEDIDOS_CONSECUTIVO=?,TB_PEDIDOS_TIPO_PRODUCTO=?,TB_PEDIDOS_CONTENIDO_CAJA=?,TB_PEDIDOS_ID_ASESORA=?,TB_PEDIDOS_CEDULA=?,TB_PEDIDOS_NOMBRE_ASESORA=?,TB_PEDIDOS_DIRECCION_ASESORA=?,TB_PEDIDOS_DPTO_ASESORA=?,TB_PEDIDOS_BARRIO_ASESORA=?,TB_PEDIDOS_VEREDA=?,TB_PEDIDOS_MUNICIPIO_ENVIEXPRESS=?,TB_PEDIDOS_CELULAR_ASESORA=?,TB_PEDIDOS_MOVIL_ASESORA=?,TB_PEDIDOS_AUDITAR=?,TB_PEDIDOS_CAJAS=?,TIEMPO_TRANSITO_BODEGA=?,TIEMPO_BODEGA_REPARTO=?,TIEMPO_BODEGA_DIGITALIZADO=?,TIEMPO_TRANSITO_DIGITALIZADO=?,TIEMPO_REPARTO_DIGITALIZADO=?,TIPO_DE_CARGA=?,TIPO_DESTINO=?,PROMESA_HRS=?,ANS=?,METODO_DE_PAGO=?,ESTADO=?,EN_BODEGA_FECHA=?,EN_REPARTO_FECHA=?,ESTADO_ENTREGADO=?,EN_ENTREGADO_FECHA=?,DIGITALIZADO_FECHA=?,SINIESTRO_FECHA=?,ESTADO_DIGITALIZADO=?,ESTADO_NO_ENTREGADO=?,EN_NO_ENTREGADO_FECHA=?,ESTADO_REENVIO=?,EN_REENVIO_FECHA=?,EN_RETORNO_FECHA=?,REZAGO_FECHA=?,NOVEDAD=?,NOTA=?,NOTAS_DE_OPERACION=?,CEDI=?,ACTIVO=?,FECHA_HORA=?,FECHA=?,CODIGO_DE_CARGA=?,ORDEN_DE_SERVICIO=?,ORDEN_DE_DESPACHO=?,PLACA=?,PLACA_DE_REPARTO=?,TRANSPORTADOR=?,FECHA_CARGA=?,ENCONTRADO_EN_CONTEO=?,CONSECUTIVO_CONTEO=?,CODIGO_DE_CARGUE=?,MANIFIESTO_URBANO=?,CODIGO_DE_REENVIO=?,CODIGO_DE_RETORNO=?,ESTADO_SEGMENTACION_DE_CONTEO=?,ESTADO_CODIGO_DE_ZONA=?,CODIGO_CIUDAD=?,MAIL_GROUP=?,PLACA_MP=?,NOMBRE_CONDUCTOR=?,LINK=?,FOTOGRAFIA=?,TEST=?,USUARIO_REGISTRO=?,USUARIO_EN_BODEGA=?,USUARIO_EN_REPARTO=?,TOKEN=?,DESPACHO_API=?,DESPACHO_ID=?,CODE_STATUS=?,EN_TRANSBORDO_FECHA=?,CHECK_TRANSITO=?,CHECK_TRANSITO_A_CEDI=?,CHECK_EN_BODEGA_VERIFICACION=?,CHECK_EN_BODEGA=?,CHECK_EN_REPARTO=?,CHECK_DIGITALIZADO=?,RADICADO=?,RADICADOSC=?,ESTADO_MOVE=?,ESTADO_MOVE_RECORDS=?,ESTADO_MOVE_EC=?,CODIGO_FLETE=?,VR_UNITARIO_DIST=?,VR_UNITARIO_VEREDA_DIST=?,VR_ADICIONAL_DIST=?,VR_FLETE_DIST=?,OTROS_COSTOS_DIST=?,PRE_LIQUIDACION=?,FECHA_PRE_LIQUIDACION=?,ESTADO_PRE_LIQUIDACION=?,REGISTRO_MOVIDO_PRE_LIQUIDACION=?,ORDEN_DE_COMPRA=?,FECHA_ORDEN_DE_COMPRA=?,VR_FAC=?,VR_FTE_FAC=?,NO_FAC=?,FECHA_FAC=?,ESTADO_TRACKING=?,ESTADO_PRELIQUIDACION=?,NTF_EN_REPARTO=?,NTF_DIGITALIZADO=? WHERE TB_PEDIDOS_BARCODE_CAJA=? ",
      [
        datos.TB_PEDIDOS_NIT,
        datos.TB_PEDIDOS_CLIENTE,
        datos.TB_PEDIDOS_MARCA,
        datos.TB_PEDIDOS_CODIGO_ZONA,
        datos.TB_PEDIDOS_NOMBRE_ZONA,
        datos.TB_PEDIDOS_CIUDAD,
        datos.TB_PEDIDOS_CAMPANA,
        datos.TB_PEDIDOS_FECHA,
        datos.TB_PEDIDOS_NRO_FACTURA,
        datos.TB_PEDIDOS_NRO_PEDIDO,
        datos.TB_PEDIDOS_CONSECUTIVO,
        datos.TB_PEDIDOS_TIPO_PRODUCTO,
        datos.TB_PEDIDOS_CONTENIDO_CAJA,
        datos.TB_PEDIDOS_ID_ASESORA,
        datos.TB_PEDIDOS_CEDULA,
        datos.TB_PEDIDOS_NOMBRE_ASESORA,
        datos.TB_PEDIDOS_DIRECCION_ASESORA,
        datos.TB_PEDIDOS_DPTO_ASESORA,
        datos.TB_PEDIDOS_BARRIO_ASESORA,
        datos.TB_PEDIDOS_VEREDA,
        datos.TB_PEDIDOS_MUNICIPIO_ENVIEXPRESS,
        datos.TB_PEDIDOS_CELULAR_ASESORA,
        datos.TB_PEDIDOS_MOVIL_ASESORA,
        datos.TB_PEDIDOS_AUDITAR,
        datos.TB_PEDIDOS_CAJAS,
        datos.TIEMPO_TRANSITO_BODEGA,
        datos.TIEMPO_BODEGA_REPARTO,
        datos.TIEMPO_BODEGA_DIGITALIZADO,
        datos.TIEMPO_TRANSITO_DIGITALIZADO,
        datos.TIEMPO_REPARTO_DIGITALIZADO,
        datos.TIPO_DE_CARGA,
        datos.TIPO_DESTINO,
        datos.PROMESA_HRS,
        datos.ANS,
        datos.METODO_DE_PAGO,
        datos.ESTADO,
        datos.EN_BODEGA_FECHA,
        datos.EN_REPARTO_FECHA,
        datos.ESTADO_ENTREGADO,
        datos.EN_ENTREGADO_FECHA,
        datos.DIGITALIZADO_FECHA,
        datos.SINIESTRO_FECHA,
        datos.ESTADO_DIGITALIZADO,
        datos.ESTADO_NO_ENTREGADO,
        datos.EN_NO_ENTREGADO_FECHA,
        datos.ESTADO_REENVIO,
        datos.EN_REENVIO_FECHA,
        datos.EN_RETORNO_FECHA,
        datos.REZAGO_FECHA,
        datos.NOVEDAD,
        datos.NOTA,
        datos.NOTAS_DE_OPERACION,
        datos.CEDI,
        datos.ACTIVO,
        datos.FECHA_HORA,
        datos.FECHA,
        datos.CODIGO_DE_CARGA,
        datos.ORDEN_DE_SERVICIO,
        datos.ORDEN_DE_DESPACHO,
        datos.PLACA,
        datos.PLACA_DE_REPARTO,
        datos.TRANSPORTADOR,
        datos.FECHA_CARGA,
        datos.ENCONTRADO_EN_CONTEO,
        datos.CONSECUTIVO_CONTEO,
        datos.CODIGO_DE_CARGUE,
        datos.MANIFIESTO_URBANO,
        datos.CODIGO_DE_REENVIO,
        datos.CODIGO_DE_RETORNO,
        datos.ESTADO_SEGMENTACION_DE_CONTEO,
        datos.ESTADO_CODIGO_DE_ZONA,
        datos.CODIGO_CIUDAD,
        datos.MAIL_GROUP,
        datos.PLACA_MP,
        datos.NOMBRE_CONDUCTOR,
        datos.LINK,
        datos.FOTOGRAFIA,
        datos.TEST,
        datos.USUARIO_REGISTRO,
        datos.USUARIO_EN_BODEGA,
        datos.USUARIO_EN_REPARTO,
        datos.TOKEN,
        datos.DESPACHO_API,
        datos.DESPACHO_ID,
        datos.CODE_STATUS,
        datos.EN_TRANSBORDO_FECHA,
        datos.CHECK_TRANSITO,
        datos.CHECK_TRANSITO_A_CEDI,
        datos.CHECK_EN_BODEGA_VERIFICACION,
        datos.CHECK_EN_BODEGA,
        datos.CHECK_EN_REPARTO,
        datos.CHECK_DIGITALIZADO,
        datos.RADICADO,
        datos.RADICADOSC,
        datos.ESTADO_MOVE,
        datos.ESTADO_MOVE_RECORDS,
        datos.ESTADO_MOVE_EC,
        datos.CODIGO_FLETE,
        datos.VR_UNITARIO_DIST,
        datos.VR_UNITARIO_VEREDA_DIST,
        datos.VR_ADICIONAL_DIST,
        datos.VR_FLETE_DIST,
        datos.OTROS_COSTOS_DIST,
        datos.PRE_LIQUIDACION,
        datos.FECHA_PRE_LIQUIDACION,
        datos.ESTADO_PRE_LIQUIDACION,
        datos.REGISTRO_MOVIDO_PRE_LIQUIDACION,
        datos.ORDEN_DE_COMPRA,
        datos.FECHA_ORDEN_DE_COMPRA,
        datos.VR_FAC,
        datos.VR_FTE_FAC,
        datos.NO_FAC,
        datos.FECHA_FAC,
        datos.ESTADO_TRACKING,
        datos.ESTADO_PRELIQUIDACION,
        datos.NTF_EN_REPARTO,
        datos.NTF_DIGITALIZADO,
        datos.TB_PEDIDOS_BARCODE_CAJA,
      ]
    );

    return query;
  };

  getPedidosDigitalizadosModel = async () => {
    const [query] = await connection.query(
      "INSERT INTO TB_PEDIDOS_TRIGGRER SELECT * FROM TB_PEDIDOS_DIGITALIZADO WHERE 1"
    );
    return query;
  };
}

export default EspejoModel;
